name: Unit tests

on:
  push:
    branches: [ master ]
  pull:
    branches: [ master ]


jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: make test
        run: make test
      
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-file
          path: test

  run-test:
    steps:
      - uses: actions/download@v2
        with:
          name: test-file

      - name: run test
      - shell: bash
        run: test

