name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: make test
        run: make test

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-file
          path: test

  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: download-artifact
        uses: actions/download-artifact@v2
        with:
          name: test-file

      - name: run test
        shell: bash
        run: test

