name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build-run-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: init submodule
        run: git submodule update --init

      - name: make test
        run: make test

      - name: put output of test in file
        run: |
          ./test > test_output
        shell: bash
      
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-file
          path: test_output
